name: Deploy Flask API to Cloud Run

on:
  push:
    branches:
      - main  # kamu bisa ganti ke nama branch lain jika berbeda

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: notional-radio-459609-h5
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/notional-radio-459609-h5/flask-api-repo/flask-api-gcp .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/notional-radio-459609-h5/flask-api-repo/flask-api-gcp

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-api-service \
            --image=asia-southeast2-docker.pkg.dev/notional-radio-459609-h5/flask-api-repo/flask-api-gcp \
            --platform=managed \
            --region=asia-southeast2 \
            --allow-unauthenticated
